### ISSUE TITLE
Dummy404ResponseObject undefined

### ISSUE THREAD

**Issue by dragondave** [learningequality/BasicCrawler#3]
After timing out six times with a bad website, the crawler crashes on https://github.com/learningequality/BasicCrawler/blob/79a81c464bdb40190f45ffa68c638f0d9449afe0/crawler.py#L560

I can't find where `Dummy404ResponseObject` is defined; it's also referenced in https://github.com/fle-internal/te-sushi-chef/blob/master/te_chef.py [thanks, Google]

**Comment by ivanistheone** [comment]
seems Dummy404ResponseObject was removed from code
