### ISSUE TITLE
# TODO: de-couple from ricecooker

### ISSUE THREAD

**Issue by tim-moody** [learningequality/BasicCrawler#4]
I was just about to do this when I saw this comment. Can you give me some pointers?
https://github.com/learningequality/ricecooker/blob/master/ricecooker/utils/caching.py
has imports from cachecontrol 
do I just steal class CacheForeverHeuristic(BaseHeuristic):
or is there something simpler?
btw. I got a huge number of errors trying to pip install this because of all the dependencies and their dependencies.

**Comment by tim-moody** [comment]
# Don't use this - call logging.getLogger(__name__) from each
# individual module. Logging is configured centrally by calling
# setup_logging()
LOGGER = logging.getLogger()

**Comment by ivanistheone** [comment]
pushed some de-ricecookerification edits

tried the examples and seem to work just like before
